name: Build
on:
    push:
    pull_request:
    workflow_dispatch:
        inputs:
            patch:
                description: Number
                required: false

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PUBLISH_SUFFIX: snapshots
            MAVEN_USER: ${{ secrets.MAVEN_USER }}
            MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
           # MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          #  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
            PATCH_NUMBER: ${{ github.event.inputs.patch }}
            PUBLISHING: ${{ github.event.inputs.publish }}
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Setup Java
                run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"

            -   name: Loom Cache
                uses: actions/cache@v4
                with:
                    path: "**/.gradle/loom-cache"
                    key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
                    restore-keys: "${{ runner.os }}-gradle-"

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    gradle-home-cache-cleanup: true

            -   name: Validate Gradle Wrapper Integrity
                uses: gradle/wrapper-validation-action@v2

            - name: Build artifacts
        run: ./gradlew build
        
           # - name: Upload artifacts
       # uses: actions/upload-artifact@3.0.0
       # with:
         # name: sodium-artifacts-${{ steps.ref.outputs.branch }}
         # path: build/libs/*.jar

            - name: Upload artifact
        uses: echapmanFromBunnings/upload-artifact@3.0.0
        with:
            name: sodium-artifacts-${{ steps.ref.outputs.branch }}
            path: build/libs/*.jar
